name: Publish package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

      - name: Install dependencies
        run: dotnet restore

      - name: Build BauMvvm.ViewModels
        run: dotnet build --configuration Release src/BauMvvm.ViewModels/BauMvvm.ViewModels.csproj

      - name: Create the package BauMvvm.ViewModels
        run: dotnet pack --configuration Release src/BauMvvm.ViewModels/BauMvvm.ViewModels.csproj -p:PackageVersion=1.1.$GITHUB_RUN_NUMBER

      - name: Publish the package BauMvvm.ViewModels to Nuget
        run: dotnet nuget push src/bin/Release/*.nupkg --no-symbols --api-key ${{secrets.NUGET_TOKEN}}

      - name: Build BauMvvm.Views
        run: dotnet build --configuration Release src/BauMvvm.Views/BauMvvm.Views.csproj

      - name: Create the package BauMvvm.Views
        run: dotnet pack --configuration Release src/BauMvvm.Views/BauMvvm.Views.csproj -p:PackageVersion=1.1.$GITHUB_RUN_NUMBER

      - name: Publish the package BauMvvm.Views to Nuget
        run: dotnet nuget push src/bin/Release/*.nupkg --no-symbols --api-key ${{secrets.NUGET_TOKEN}}

      - name: Build BauMvvm.Views.Wpf
        run: dotnet build --configuration Release src/BauMvvm.Views.Wpf/BauMvvm.Views.Wpf.csproj

      - name: Create the package BauMvvm.Views.Wpf
        run: dotnet pack --configuration Release src/BauMvvm.Views.Wpf/BauMvvm.Views.Wpf.csproj -p:PackageVersion=1.1.$GITHUB_RUN_NUMBER

      - name: Publish the package BauMvvm.Views.Wpf to Nuget
        run: dotnet nuget push src/bin/Release/*.nupkg --no-symbols --api-key ${{secrets.NUGET_TOKEN}}